# Change these first
owner: amokster88 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
runner: "[self-hosted]"

sites:
  - name: EM-X
    url: $EM_X
    __dangerous__insecure: true
    __dangerous__body_down_if_text_missing: "Emby Server"
  - name: ANDROMEDA
    url: $EM_ANDROMEDA
    __dangerous__body_down_if_text_missing: "Emby Server"
  - name: CASSIOPEIA
    url: $EM_CASSIOPEIA
    __dangerous__body_down_if_text_missing: "Emby Server"
  - name: COMET
    url: $EM_COMET
    __dangerous__body_down_if_text_missing: "Emby Server"
  - name: EON
    url: $EM_EON
    __dangerous__body_down_if_text_missing: "Emby Server"
  - name: NEBULON
    url: $EM_NEBULON
    __dangerous__body_down_if_text_missing: "Emby Server"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.luke.casa
  #baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Servers Status
  theme: dark
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  #navbar:
    #- title: Servers Status
    #  href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: This page is open source, powered by [Upptime](https://upptime.js.org)
